### ISSUE TITLE
feature 디버그 요망

### ISSUE THREAD

**Issue by DooHwanKim92** [DooHwanKim92/githubflow#5]
### 이슈
- 소프트웨어 이슈
- 소프트웨어 없슈

### TODO

- [ ] 오산낙지
- [ ] 아메리카노

**Comment by TwinOgre** [comment]
### 야호

**Comment by DooHwanKim92** [comment]
해당 이슈는 오산낙지가 맛이 없기 때문에 won't fix 하고 close 하겠습니다.
